import Link from "next/link";
import {
  ArrowRight,
  BarChart3,
  BatteryCharging,
  Building2,
  CheckCircle2,
  CircleDollarSign,
  FileCheck2,
  Gauge,
  Handshake,
  LineChart,
  LockKeyhole,
  ReceiptText,
  ShieldCheck,
  Sun,
  Wrench,
  Zap,
} from "lucide-react";

import { PageHero } from "@/components/shared/page-hero";
import { CtaBanner } from "@/components/shared/cta-banner";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export const metadata = {
  title: "Commercial Solar PPA — BrightGrid Energy",
  description:
    "Explore Power Purchase Agreements for commercial solar. A third-party funder can finance and own the solar asset while your business purchases the electricity generated under an agreed PPA.",
};

const HOW_IT_WORKS = [
  {
    number: "01",
    icon: Building2,
    title: "We assess your site",
    description:
      "We understand your buildings, electricity demand, available roof space, operating profile and energy objectives.",
  },
  {
    number: "02",
    icon: Sun,
    title: "We develop the solar project",
    description:
      "The technical design is developed around the site's electricity demand, generation potential and grid requirements.",
  },
  {
    number: "03",
    icon: CircleDollarSign,
    title: "A funding partner funds the asset",
    description:
      "Where suitable, an investor or asset owner provides the capital required to develop and install the solar system.",
  },
  {
    number: "04",
    icon: Zap,
    title: "The solar system generates",
    description:
      "The system produces electricity on-site for the business to use, subject to the agreed commercial structure.",
  },
  {
    number: "05",
    icon: ReceiptText,
    title: "You pay for the energy",
    description:
      "Instead of purchasing the entire solar asset upfront, the business purchases electricity under the agreed PPA pricing structure.",
  },
  {
    number: "06",
    icon: Wrench,
    title: "The asset is operated",
    description:
      "The asset owner or appointed operator manages the responsibilities defined within the PPA and operating agreements.",
  },
];

const BENEFITS = [
  {
    icon: CircleDollarSign,
    title: "Reduce upfront capital requirements",
    description:
      "A PPA can allow a business to access on-site solar without purchasing the entire generation asset upfront.",
  },
  {
    icon: Gauge,
    title: "Potentially improve energy economics",
    description:
      "The PPA price can be structured against the expected economics of the project and the customer's electricity requirements.",
  },
  {
    icon: ShieldCheck,
    title: "Asset ownership can sit elsewhere",
    description:
      "The funding partner or asset owner can retain ownership of the solar infrastructure during the agreed term.",
  },
  {
    icon: Wrench,
    title: "Operational responsibility",
    description:
      "Depending on the contract, the asset owner or operator can manage monitoring, maintenance and other operational responsibilities.",
  },
  {
    icon: LineChart,
    title: "Long-term visibility",
    description:
      "A defined PPA structure can provide greater visibility over the price paid for the agreed electricity output.",
  },
  {
    icon: BatteryCharging,
    title: "Solar + storage potential",
    description:
      "Where technically and commercially appropriate, battery storage can be considered alongside the solar project.",
  },
];

const WHO_IT_SUITS = [
  "Warehouses",
  "Factories",
  "Farms",
  "Schools & education estates",
  "Retail portfolios",
  "Hotels",
  "Property portfolios",
  "Industrial sites",
];

const CUSTOMER_SIDE = [
  "Uses the electricity generated by the system",
  "Pays the agreed PPA price under the contract",
  "Provides agreed site access",
  "Continues operating its normal business",
  "Receives agreed reporting and information",
];

const ASSET_SIDE = [
  "Provides or arranges project funding",
  "Owns the solar asset under the agreed structure",
  "Coordinates system operation",
  "Manages agreed maintenance responsibilities",
  "Monitors system performance",
  "Coordinates repairs where covered",
];

export default function PPAPage() {
  return (
    <>
      {/* HERO */}
      <PageHero
        tone="dark"
        eyebrow="Power Purchase Agreements"
        title="Get the solar. Without having to buy the solar."
        description="A commercial PPA can allow your business to access on-site renewable electricity while a funding partner provides and owns the solar asset under an agreed long-term structure."
        ctaLabel="Explore a PPA for your site"
        ctaHref="#assessment"
      />

      {/* INTRO */}
      <section className="section">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center">
            <div>
              <p className="eyebrow">Solar as an energy service</p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Your business needs electricity. It doesn't necessarily need
                to own the power station.
              </h2>
            </div>

            <div className="space-y-5 text-muted-foreground">
              <p>
                A Power Purchase Agreement, or PPA, is a long-term commercial
                agreement for the purchase of electricity generated by an
                energy asset.
              </p>

              <p>
                In a solar PPA, a funding partner or asset owner can finance
                and own the solar installation while the customer purchases
                electricity generated by the system under agreed contractual
                terms.
              </p>

              <p>
                For the right site, this can create a route to on-site
                renewable generation without requiring the business to fund
                the entire solar installation upfront.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* SIMPLE MODEL */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="mx-auto max-w-5xl">
            <div className="grid gap-4 md:grid-cols-3">
              <FlowCard
                icon={CircleDollarSign}
                eyebrow="01"
                title="Funder"
                description="Provides or arranges capital for the energy asset."
              />

              <FlowCard
                icon={Sun}
                eyebrow="02"
                title="Solar asset"
                description="Installed on the customer's site and generates electricity."
              />

              <FlowCard
                icon={Building2}
                eyebrow="03"
                title="Business"
                description="Uses the generated electricity and pays according to the PPA."
              />
            </div>

            <div className="mt-6 flex flex-wrap items-center justify-center gap-3 text-xs text-muted-foreground">
              <span className="rounded-full border border-border bg-background px-4 py-2">
                Capital
              </span>

              <ArrowRight className="size-4" />

              <span className="rounded-full border border-border bg-background px-4 py-2">
                Solar infrastructure
              </span>

              <ArrowRight className="size-4" />

              <span className="rounded-full border border-border bg-background px-4 py-2">
                Renewable electricity
              </span>

              <ArrowRight className="size-4" />

              <span className="rounded-full border border-border bg-background px-4 py-2">
                PPA payment
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="section">
        <div className="container">
          <div className="max-w-2xl">
            <p className="eyebrow">How a commercial PPA works</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              From site assessment to long-term energy supply.
            </h2>

            <p className="mt-4 text-muted-foreground">
              The exact structure varies between projects, but the process
              typically follows this journey.
            </p>
          </div>

          <div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            {HOW_IT_WORKS.map((step) => {
              const Icon = step.icon;

              return (
                <div
                  key={step.number}
                  className="border-t-2 border-primary pt-5"
                >
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-xs text-muted-foreground">
                      {step.number}
                    </span>

                    <Icon className="size-5 text-muted-foreground" />
                  </div>

                  <h3 className="mt-5 font-display text-xl font-medium">
                    {step.title}
                  </h3>

                  <p className="mt-2 text-sm leading-6 text-muted-foreground">
                    {step.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* BENEFITS */}
      <section className="section bg-black text-white">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr]">
            <div>
              <p className="eyebrow text-white/60">
                Why businesses consider PPAs
              </p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Turn solar from a capital project into an energy strategy.
              </h2>

              <p className="mt-5 max-w-md text-white/55">
                A PPA can change the way a business approaches renewable
                generation by separating electricity consumption from asset
                ownership.
              </p>
            </div>

            <div className="grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2">
              {BENEFITS.map((item) => {
                const Icon = item.icon;

                return (
                  <div
                    key={item.title}
                    className="bg-black p-7"
                  >
                    <Icon className="size-6" />

                    <h3 className="mt-6 font-display text-xl font-medium">
                      {item.title}
                    </h3>

                    <p className="mt-2 text-sm leading-6 text-white/50">
                      {item.description}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* RESPONSIBILITY SPLIT */}
      <section className="section">
        <div className="container">
          <div className="text-center">
            <p className="eyebrow">The responsibility split</p>

            <h2 className="mx-auto mt-3 max-w-3xl text-balance font-display text-3xl font-medium md:text-5xl">
              Your business operates the site. The asset owner manages the
              energy infrastructure.
            </h2>
          </div>

          <div className="mx-auto mt-12 grid max-w-5xl overflow-hidden rounded-3xl border border-border md:grid-cols-2">
            {/* CUSTOMER */}
            <div className="p-8 md:p-10">
              <div className="flex size-11 items-center justify-center rounded-xl bg-secondary">
                <Building2 className="size-5" />
              </div>

              <h3 className="mt-6 font-display text-2xl font-medium">
                Your business
              </h3>

              <p className="mt-2 text-sm text-muted-foreground">
                Your focus stays on your operation.
              </p>

              <div className="mt-7 space-y-4">
                {CUSTOMER_SIDE.map((item) => (
                  <div
                    key={item}
                    className="flex items-start gap-3 text-sm"
                  >
                    <CheckCircle2 className="mt-0.5 size-4 shrink-0" />
                    {item}
                  </div>
                ))}
              </div>
            </div>

            {/* ASSET OWNER */}
            <div className="bg-secondary/50 p-8 md:p-10">
              <div className="flex size-11 items-center justify-center rounded-xl bg-background">
                <ShieldCheck className="size-5" />
              </div>

              <h3 className="mt-6 font-display text-2xl font-medium">
                Funder / asset owner
              </h3>

              <p className="mt-2 text-sm text-muted-foreground">
                Responsibilities are defined by the PPA and associated
                agreements.
              </p>

              <div className="mt-7 space-y-4">
                {ASSET_SIDE.map((item) => (
                  <div
                    key={item}
                    className="flex items-start gap-3 text-sm"
                  >
                    <CheckCircle2 className="mt-0.5 size-4 shrink-0" />
                    {item}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* PRICE MODEL */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center">
            <div>
              <p className="eyebrow">The commercial model</p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Pay for the electricity. Not necessarily the entire asset.
              </h2>

              <p className="mt-5 text-muted-foreground">
                Instead of purchasing the solar installation outright, the
                customer enters into an agreement to purchase electricity
                generated by the system.
              </p>
            </div>

            <Card className="overflow-hidden">
              <div className="border-b border-border p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
                      Illustrative PPA economics
                    </p>

                    <h3 className="mt-2 font-display text-xl font-medium">
                      Electricity generated on-site
                    </h3>
                  </div>

                  <Badge variant="leaf">Example only</Badge>
                </div>
              </div>

              <div className="grid gap-px bg-border sm:grid-cols-3">
                <Metric
                  icon={Sun}
                  label="Generation"
                  value="Solar"
                />

                <Metric
                  icon={ReceiptText}
                  label="Purchase"
                  value="PPA rate"
                />

                <Metric
                  icon={BarChart3}
                  label="Comparison"
                  value="Grid cost"
                />
              </div>

              <div className="p-6">
                <p className="text-sm leading-6 text-muted-foreground">
                  The financial outcome depends on the agreed PPA price,
                  electricity consumption, generation profile, grid prices,
                  contract term, system performance and other project-specific
                  factors.
                </p>
              </div>
            </Card>
          </div>
        </div>
      </section>

      {/* WHO IT SUITS */}
      <section className="section">
        <div className="container">
          <div className="max-w-2xl">
            <p className="eyebrow">Who can consider a PPA?</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              Particularly interesting for energy-intensive sites and
              portfolios.
            </h2>
          </div>

          <div className="mt-10 flex flex-wrap gap-3">
            {WHO_IT_SUITS.map((item) => (
              <span
                key={item}
                className="rounded-full border border-border bg-secondary/50 px-5 py-3 text-sm font-medium"
              >
                {item}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* PORTFOLIO */}
      <section className="section bg-charcoal text-cream">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr]">
            <div>
              <p className="eyebrow text-leaf-light">
                Multi-site opportunities
              </p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                One strategy across an entire property portfolio.
              </h2>

              <p className="mt-5 max-w-md text-sm leading-7 text-cream/60">
                Landlords, property companies and organisations with multiple
                sites can potentially assess several buildings together,
                creating a larger commercial energy opportunity.
              </p>
            </div>

            <div className="space-y-4">
              {[
                "Identify suitable sites",
                "Assess electricity demand",
                "Model generation across the portfolio",
                "Evaluate grid and connection constraints",
                "Build a combined project opportunity",
                "Explore funding and PPA structures",
              ].map((item, index) => (
                <div
                  key={item}
                  className="flex items-center gap-5 border-b border-white/10 pb-4"
                >
                  <span className="font-mono text-xs text-white/30">
                    0{index + 1}
                  </span>

                  <span className="text-sm text-white/75">
                    {item}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* BATTERY */}
      <section className="section">
        <div className="container">
          <div className="grid gap-10 lg:grid-cols-2">
            <Card className="p-8 md:p-10">
              <BatteryCharging className="size-7" />

              <h2 className="mt-6 font-display text-2xl font-medium md:text-3xl">
                Solar + battery
              </h2>

              <p className="mt-4 text-muted-foreground">
                Battery storage can potentially be incorporated into a
                commercial energy project where it improves the technical or
                commercial case.
              </p>

              <Link
                href="/battery"
                className="mt-7 inline-flex items-center text-sm font-medium"
              >
                Explore battery flexibility
                <ArrowRight className="ml-2 size-4" />
              </Link>
            </Card>

            <Card className="p-8 md:p-10">
              <Handshake className="size-7" />

              <h2 className="mt-6 font-display text-2xl font-medium md:text-3xl">
                Solar without operational complexity
              </h2>

              <p className="mt-4 text-muted-foreground">
                A properly structured PPA can place many asset-management
                responsibilities with the asset owner or operator, allowing
                your facilities team to focus on the business.
              </p>

              <Link
                href="/commercial/operations"
                className="mt-7 inline-flex items-center text-sm font-medium"
              >
                See commercial operations
                <ArrowRight className="ml-2 size-4" />
              </Link>
            </Card>
          </div>
        </div>
      </section>

      {/* CONTRACT DETAILS */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="mx-auto max-w-4xl rounded-3xl border border-border bg-background p-8 md:p-12">
            <div className="flex size-12 items-center justify-center rounded-xl bg-secondary">
              <LockKeyhole className="size-6" />
            </div>

            <h2 className="mt-6 font-display text-2xl font-medium md:text-3xl">
              The contract defines the details.
            </h2>

            <p className="mt-4 text-sm leading-7 text-muted-foreground">
              PPAs are long-term commercial agreements and should be assessed
              carefully. Pricing, contract duration, ownership, maintenance,
              insurance, performance guarantees, metering, site access,
              termination provisions, change-of-control provisions and
              end-of-term arrangements should all be clearly defined.
            </p>

            <p className="mt-4 text-sm leading-7 text-muted-foreground">
              BrightGrid can help develop the technical opportunity and
              commercial project structure, while the final contractual terms
              should be reviewed and agreed by the relevant parties and their
              advisers.
            </p>
          </div>
        </div>
      </section>

      {/* ASSESSMENT */}
      <section id="assessment" className="section">
        <div className="container">
          <div className="mx-auto max-w-4xl rounded-3xl border border-border p-8 md:p-12">
            <div className="flex flex-col gap-8 md:flex-row">
              <div className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-secondary">
                <FileCheck2 className="size-6" />
              </div>

              <div>
                <p className="eyebrow">PPA assessment</p>

                <h2 className="mt-3 font-display text-3xl font-medium md:text-4xl">
                  Let's see whether your site is PPA-ready.
                </h2>

                <p className="mt-4 max-w-2xl text-muted-foreground">
                  Tell us about your site, electricity consumption, property
                  ownership and objectives. We'll assess the project
                  fundamentals and determine what should happen next.
                </p>

                <div className="mt-8 grid gap-3 sm:grid-cols-3">
                  {[
                    "Site & property",
                    "Energy demand",
                    "Commercial objectives",
                  ].map((item, index) => (
                    <div
                      key={item}
                      className="rounded-xl bg-secondary/50 p-4"
                    >
                      <span className="font-mono text-xs text-muted-foreground">
                        0{index + 1}
                      </span>

                      <p className="mt-2 text-sm font-medium">
                        {item}
                      </p>
                    </div>
                  ))}
                </div>

                <Link
                  href="/commercial#assessment"
                  className="mt-8 inline-flex items-center rounded-lg bg-primary px-5 py-3 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90"
                >
                  Discuss a commercial PPA
                  <ArrowRight className="ml-2 size-4" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <CtaBanner
        title="Your roof could become an energy asset."
        description="Let's assess the technical, energy and commercial opportunity for your site."
        href="#assessment"
        cta="Explore a PPA"
      />
    </>
  );
}

function FlowCard({
  icon: Icon,
  eyebrow,
  title,
  description,
}: {
  icon: typeof Sun;
  eyebrow: string;
  title: string;
  description: string;
}) {
  return (
    <Card className="p-7">
      <div className="flex items-center justify-between">
        <span className="font-mono text-xs text-muted-foreground">
          {eyebrow}
        </span>

        <Icon className="size-5 text-muted-foreground" />
      </div>

      <h3 className="mt-7 font-display text-xl font-medium">
        {title}
      </h3>

      <p className="mt-2 text-sm leading-6 text-muted-foreground">
        {description}
      </p>
    </Card>
  );
}

function Metric({
  icon: Icon,
  label,
  value,
}: {
  icon: typeof Sun;
  label: string;
  value: string;
}) {
  return (
    <div className="bg-background p-6">
      <Icon className="size-5" />

      <p className="mt-5 text-xs text-muted-foreground">
        {label}
      </p>

      <p className="mt-1 font-medium">
        {value}
      </p>
    </div>
  );
}