import Link from "next/link";
import {
    AlertTriangle,
  ArrowRight,
  BatteryCharging,
  Building2,
  CheckCircle2,
  Factory,
  Gauge,
  Layers3,
  LineChart,
  Network,
  PlugZap,
  ShieldCheck,
  Sparkles,
  Sun,
  TrendingDown,
  Truck,
  Wrench,
  Zap,
} from "lucide-react";

import { PageHero } from "@/components/shared/page-hero";
import { CtaBanner } from "@/components/shared/cta-banner";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export const metadata = {
  title: "Industrial Solar & Energy Systems — BrightGrid Energy",
  description:
    "Industrial solar, battery storage, EV charging, energy management and PPAs designed around manufacturing, processing, logistics and industrial operations.",
};

const INDUSTRIAL_LOADS = [
  {
    icon: Factory,
    title: "Manufacturing",
    description:
      "Support production lines, machinery, compressors and other high-demand industrial equipment with on-site renewable generation.",
  },
  {
    icon: Gauge,
    title: "Continuous operations",
    description:
      "Analyse operating schedules and electricity demand across shifts, weekends and seasonal production patterns.",
  },
  {
    icon: Layers3,
    title: "Processing",
    description:
      "Energy strategies for food processing, materials handling, fabrication and other electricity-intensive operations.",
  },
  {
    icon: Truck,
    title: "Logistics",
    description:
      "Combine warehouse energy demand with fleet charging, depot infrastructure and solar generation.",
  },
  {
    icon: PlugZap,
    title: "Electrification",
    description:
      "Prepare for increasing electricity demand from machinery, heating, vehicles and industrial equipment.",
  },
  {
    icon: BatteryCharging,
    title: "Energy storage",
    description:
      "Use battery storage to shift energy, manage demand and explore additional flexibility opportunities.",
  },
];

const ENERGY_SYSTEM = [
  {
    number: "01",
    icon: Sun,
    title: "Solar generation",
    description:
      "Generate electricity directly at the industrial site and prioritise production against the site's actual demand.",
  },
  {
    number: "02",
    icon: BatteryCharging,
    title: "Battery storage",
    description:
      "Store surplus generation and strategically discharge energy when it can provide greater operational value.",
  },
  {
    number: "03",
    icon: Zap,
    title: "EV & fleet charging",
    description:
      "Integrate vehicle charging into the site's wider electrical infrastructure instead of treating it as a separate project.",
  },
  {
    number: "04",
    icon: Gauge,
    title: "Energy management",
    description:
      "Monitor generation, consumption, battery behaviour, charging and system performance from a connected platform.",
  },
];

const ASSESSMENT_POINTS = [
  "Roof area and structural suitability",
  "Ground and carport opportunities",
  "Historical electricity consumption",
  "Half-hourly demand profile",
  "Production and operating schedules",
  "Existing electrical infrastructure",
  "Grid connection and export limitations",
  "Battery storage opportunities",
  "Fleet and EV charging requirements",
  "Future electrification plans",
];

const INDUSTRIAL_BENEFITS = [
  {
    icon: TrendingDown,
    title: "Reduce grid dependency",
    description:
      "Generate a greater proportion of your electricity requirements directly on-site.",
  },
  {
    icon: Sun,
    title: "Use your roof productively",
    description:
      "Turn suitable industrial roof space into an energy-producing asset.",
  },
  {
    icon: BatteryCharging,
    title: "Increase energy flexibility",
    description:
      "Battery storage can help move electricity through time and support changing site requirements.",
  },
  {
    icon: LineChart,
    title: "Understand performance",
    description:
      "Monitor generation, consumption and system performance over the lifetime of the project.",
  },
];

const FINANCING = [
  {
    title: "Capital purchase",
    description:
      "The business funds and owns the system, giving it direct ownership of the installed energy infrastructure.",
  },
  {
    title: "Power Purchase Agreement",
    description:
      "An external asset owner may fund the installation while the business purchases electricity generated by the system under an agreed structure.",
  },
  {
    title: "Solar + battery",
    description:
      "Combine generation and storage where the site's consumption profile and technical requirements support it.",
  },
  {
    title: "Integrated energy project",
    description:
      "Bring solar, batteries, EV charging and energy management together as one long-term energy strategy.",
  },
];

const INDUSTRIAL_EXAMPLES = [
  "Manufacturing plants",
  "Food processing facilities",
  "Engineering businesses",
  "Distribution centres",
  "Cold storage",
  "Logistics depots",
  "Automotive facilities",
  "Materials processing",
  "Industrial estates",
  "Large workshops",
];

export default function IndustrialPage() {
  return (
    <>
      {/* HERO */}
      <PageHero
        tone="dark"
        eyebrow="Industrial energy"
        title="Turn industrial space into industrial energy infrastructure."
        description="Solar, battery storage, EV charging and energy management designed around manufacturing, processing, logistics and high-demand industrial operations."
        ctaLabel="Assess your industrial site"
        ctaHref="/commercial#assessment"
      />

      {/* INTRO */}
      <section className="section">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center">
            <div>
              <p className="eyebrow">Built around your operation</p>

              <h2 className="mt-3 max-w-xl text-balance font-display text-3xl font-medium md:text-5xl">
                Industrial solar starts with the electricity your operation
                actually uses.
              </h2>
            </div>

            <div className="space-y-5 text-muted-foreground">
              <p>
                An industrial building can have a huge roof, but the roof is
                only one part of the opportunity. The real question is how
                electricity moves through the site.
              </p>

              <p>
                Production schedules, machinery, refrigeration, compressors,
                heating, lighting, charging and other loads can create a
                complex energy profile that changes throughout the day.
              </p>

              <p>
                BrightGrid designs the energy system around those realities —
                combining generation, storage, charging and energy management
                where each technology makes sense.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* IMMERSIVE INDUSTRIAL VISUAL */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="overflow-hidden rounded-[2rem] border border-border bg-background">
            <div className="relative min-h-[500px] overflow-hidden bg-black text-white">
              {/* Decorative grid */}
              <div
                className="absolute inset-0 opacity-20"
                style={{
                  backgroundImage:
                    "linear-gradient(rgba(255,255,255,.08) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.08) 1px, transparent 1px)",
                  backgroundSize: "60px 60px",
                }}
              />

              <div className="absolute -right-32 -top-32 size-96 rounded-full border border-white/10" />
              <div className="absolute -bottom-40 -left-20 size-96 rounded-full border border-white/10" />

              <div className="relative z-10 grid min-h-[500px] gap-10 p-8 md:p-12 lg:grid-cols-[1fr_1.2fr] lg:items-center">
                <div>
                  <Badge
                    variant="outline"
                    className="border-white/20 bg-white/5 text-white"
                  >
                    INDUSTRIAL ENERGY SYSTEM
                  </Badge>

                  <h3 className="mt-6 max-w-xl font-display text-3xl font-medium md:text-5xl">
                    One site. Multiple energy flows.
                  </h3>

                  <p className="mt-5 max-w-lg leading-7 text-white/55">
                    Solar generation can feed production. Excess energy can
                    charge the battery. Batteries can support demand later.
                    EV charging can be coordinated with the site's electrical
                    capacity.
                  </p>

                  <Button
                    asChild
                    variant="outline"
                    className="mt-7 border-white/20 bg-white text-black hover:bg-white/90"
                  >
                    <Link href="/commercial#assessment">
                      Explore your site
                      <ArrowRight className="ml-2 size-4" />
                    </Link>
                  </Button>
                </div>

                <div className="relative">
                  <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5 backdrop-blur">
                    <div className="flex items-center justify-between border-b border-white/10 pb-4">
                      <div>
                        <p className="font-mono text-[9px] uppercase tracking-[0.2em] text-white/35">
                          Illustrative system
                        </p>

                        <p className="mt-1 text-sm font-medium">
                          Industrial energy flow
                        </p>
                      </div>

                      <span className="flex items-center gap-2 text-xs text-white/50">
                        <span className="size-2 rounded-full bg-white" />
                        Live
                      </span>
                    </div>

                    <div className="mt-5 grid gap-3 sm:grid-cols-2">
                      <EnergyNode
                        icon={Sun}
                        label="Solar"
                        value="Generating"
                      />

                      <EnergyNode
                        icon={Factory}
                        label="Production"
                        value="Operating"
                      />

                      <EnergyNode
                        icon={BatteryCharging}
                        label="Battery"
                        value="Available"
                      />

                      <EnergyNode
                        icon={Zap}
                        label="Grid"
                        value="Balanced"
                      />
                    </div>

                    <div className="mt-4 rounded-2xl border border-white/10 bg-white/[0.03] p-5">
                      <div className="flex items-center justify-between">
                        <span className="text-xs text-white/40">
                          Energy optimisation
                        </span>

                        <span className="text-xs font-medium">
                          Active
                        </span>
                      </div>

                      <div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10">
                        <div className="h-full w-[78%] rounded-full bg-white/80" />
                      </div>

                      <div className="mt-3 flex justify-between font-mono text-[9px] text-white/30">
                        <span>LOW</span>
                        <span>OPTIMISED</span>
                        <span>HIGH</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="grid border-t border-border sm:grid-cols-3">
              <IndustrialStat
                value="01"
                label="Integrated energy strategy"
              />
              <IndustrialStat
                value="24/7"
                label="Designed around operations"
              />
              <IndustrialStat
                value="∞"
                label="Future expansion considered"
              />
            </div>
          </div>
        </div>
      </section>

      {/* LOADS */}
      <section className="section">
        <div className="container">
          <div className="max-w-2xl">
            <p className="eyebrow">Industrial applications</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              Different operations. Different energy demands.
            </h2>

            <p className="mt-4 text-muted-foreground">
              We look at the equipment and processes that actually consume
              electricity rather than treating every industrial building the
              same.
            </p>
          </div>

          <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {INDUSTRIAL_LOADS.map((item) => {
              const Icon = item.icon;

              return (
                <Card
                  key={item.title}
                  className="group transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
                >
                  <CardContent className="p-6">
                    <div className="flex size-11 items-center justify-center rounded-xl bg-secondary transition-transform duration-300 group-hover:scale-110">
                      <Icon className="size-5" />
                    </div>

                    <h3 className="mt-6 font-display text-xl font-medium">
                      {item.title}
                    </h3>

                    <p className="mt-2 text-sm leading-6 text-muted-foreground">
                      {item.description}
                    </p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* ENERGY ARCHITECTURE */}
      <section className="section bg-black text-white">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr]">
            <div>
              <p className="eyebrow text-white/50">
                Integrated architecture
              </p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Build the energy system as one platform.
              </h2>

              <p className="mt-5 max-w-md leading-7 text-white/50">
                Solar, batteries and EV charging should not be designed in
                isolation. They interact with the same electrical
                infrastructure and the same operational demand.
              </p>
            </div>

            <div className="space-y-0">
              {ENERGY_SYSTEM.map((item) => {
                const Icon = item.icon;

                return (
                  <div
                    key={item.number}
                    className="group grid grid-cols-[55px_45px_1fr] gap-5 border-t border-white/10 py-7 last:border-b"
                  >
                    <span className="font-mono text-xs text-white/30">
                      {item.number}
                    </span>

                    <div className="flex size-10 items-center justify-center rounded-xl border border-white/10 bg-white/[0.03]">
                      <Icon className="size-5 text-white/70" />
                    </div>

                    <div>
                      <h3 className="font-display text-xl font-medium">
                        {item.title}
                      </h3>

                      <p className="mt-2 max-w-xl text-sm leading-6 text-white/45">
                        {item.description}
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* BENEFITS */}
      <section className="section">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center">
            <div>
              <p className="eyebrow">Why industrial solar?</p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Make your energy infrastructure work harder.
              </h2>

              <p className="mt-5 text-muted-foreground">
                Industrial energy projects can be about more than installing
                panels. The objective is to create an energy system that fits
                the operation today while leaving room for tomorrow.
              </p>

              <Button
                asChild
                variant="accent"
                className="mt-7"
              >
                <Link href="/commercial#assessment">
                  Start an assessment
                  <ArrowRight className="ml-2 size-4" />
                </Link>
              </Button>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              {INDUSTRIAL_BENEFITS.map((item) => {
                const Icon = item.icon;

                return (
                  <Card key={item.title}>
                    <CardContent className="p-6">
                      <div className="flex size-11 items-center justify-center rounded-xl bg-secondary">
                        <Icon className="size-5" />
                      </div>

                      <h3 className="mt-6 font-display text-xl font-medium">
                        {item.title}
                      </h3>

                      <p className="mt-2 text-sm leading-6 text-muted-foreground">
                        {item.description}
                      </p>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* SITE INTELLIGENCE */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[1fr_1fr]">
            <div>
              <p className="eyebrow">Industrial site intelligence</p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Before we design the system, we understand the site.
              </h2>

              <p className="mt-5 max-w-xl text-muted-foreground">
                The best industrial energy project is not necessarily the
                largest one. It is the system that works with your physical
                infrastructure, electricity profile, grid connection and
                future plans.
              </p>

              <div className="mt-8 flex items-center gap-3 rounded-2xl border border-border bg-background p-5">
                <ShieldCheck className="size-5 shrink-0" />

                <p className="text-sm leading-6 text-muted-foreground">
                  Every proposal should be based on the actual site and
                  technical information available.
                </p>
              </div>
            </div>

            <div className="grid gap-3 sm:grid-cols-2">
              {ASSESSMENT_POINTS.map((item, index) => (
                <div
                  key={item}
                  className="flex items-start gap-3 rounded-xl border border-border bg-background p-4"
                >
                  <span className="font-mono text-[10px] text-muted-foreground">
                    {String(index + 1).padStart(2, "0")}
                  </span>

                  <span className="text-sm leading-5">{item}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* LARGE ROOF */}
      <section className="section">
        <div className="container">
          <div className="relative overflow-hidden rounded-[2rem] bg-secondary p-8 md:p-12">
            <div className="absolute -right-24 -top-24 size-72 rounded-full border border-border" />
            <div className="absolute -bottom-32 right-32 size-96 rounded-full border border-border" />

            <div className="relative z-10 grid gap-12 lg:grid-cols-[1fr_0.8fr] lg:items-center">
              <div>
                <p className="eyebrow">Industrial rooftops</p>

                <h2 className="mt-3 max-w-2xl text-balance font-display text-3xl font-medium md:text-5xl">
                  Your roof could become one of your largest energy assets.
                </h2>

                <p className="mt-5 max-w-xl text-muted-foreground">
                  Large industrial roofs can provide significant usable area
                  for solar generation. But usable area, structure, roof
                  condition, orientation, access, shading and electrical
                  requirements all need to be considered.
                </p>

                <div className="mt-7 flex flex-wrap gap-2">
                  {[
                    "Roof assessment",
                    "Panel layout",
                    "Structural review",
                    "Access planning",
                    "Electrical design",
                  ].map((item) => (
                    <span
                      key={item}
                      className="rounded-full border border-border bg-background/70 px-3 py-1.5 text-xs font-medium"
                    >
                      {item}
                    </span>
                  ))}
                </div>
              </div>

              <div className="rounded-3xl border border-border bg-background p-6 shadow-sm">
                <div className="flex items-center justify-between border-b border-border pb-4">
                  <div>
                    <p className="font-mono text-[9px] uppercase tracking-[0.2em] text-muted-foreground">
                      Illustrative rooftop
                    </p>

                    <p className="mt-1 font-medium">
                      Solar layout concept
                    </p>
                  </div>

                  <Sun className="size-5" />
                </div>

                <div className="mt-6 grid grid-cols-6 gap-2">
                  {Array.from({ length: 36 }).map((_, index) => (
                    <div
                      key={index}
                      className="aspect-square rounded-sm border border-border bg-secondary transition-all hover:bg-background"
                    />
                  ))}
                </div>

                <div className="mt-6 grid grid-cols-3 gap-3">
                  <MiniMetric label="Roof" value="Assessed" />
                  <MiniMetric label="Layout" value="Optimised" />
                  <MiniMetric label="Access" value="Planned" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* BATTERY + EV */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="text-center">
            <p className="eyebrow">Beyond solar</p>

            <h2 className="mx-auto mt-3 max-w-3xl text-balance font-display text-3xl font-medium md:text-5xl">
              Industrial electrification is coming. Design for it now.
            </h2>

            <p className="mx-auto mt-4 max-w-2xl text-muted-foreground">
              Today's electricity demand may not be tomorrow's. Industrial
              sites are increasingly considering batteries, electric vehicles,
              heat pumps and other forms of electrification.
            </p>
          </div>

          <div className="mx-auto mt-12 grid max-w-5xl gap-4 md:grid-cols-3">
            <FutureCard
              icon={BatteryCharging}
              title="Battery storage"
              text="Store surplus generation and increase flexibility around site demand."
            />

            <FutureCard
              icon={Truck}
              title="Fleet electrification"
              text="Prepare depots and industrial sites for growing electric vehicle requirements."
            />

            <FutureCard
              icon={Sparkles}
              title="Future loads"
              text="Leave capacity and infrastructure options for future electrification."
            />
          </div>
        </div>
      </section>

      {/* FINANCING */}
      <section className="section bg-black text-white">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr]">
            <div>
              <p className="eyebrow text-white/50">
                Commercial structures
              </p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                The right energy project also needs the right commercial
                structure.
              </h2>

              <p className="mt-5 max-w-md leading-7 text-white/50">
                Depending on the site, objectives and project economics, there
                can be different ways to fund and operate the system.
              </p>

              <Link
                href="/ppa"
                className="mt-7 inline-flex items-center text-sm font-medium text-white underline-offset-4 hover:underline"
              >
                Explore PPAs
                <ArrowRight className="ml-2 size-4" />
              </Link>
            </div>

            <div className="grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2">
              {FINANCING.map((item) => (
                <div
                  key={item.title}
                  className="bg-black p-7"
                >
                  <h3 className="font-display text-xl font-medium">
                    {item.title}
                  </h3>

                  <p className="mt-3 text-sm leading-6 text-white/45">
                    {item.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* INDUSTRIES */}
      <section className="section">
        <div className="container">
          <div className="max-w-2xl">
            <p className="eyebrow">Where it can work</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              Built for energy-intensive environments.
            </h2>

            <p className="mt-4 text-muted-foreground">
              Every site is different, but industrial energy strategies can be
              relevant across a wide range of operations.
            </p>
          </div>

          <div className="mt-10 flex flex-wrap gap-3">
            {INDUSTRIAL_EXAMPLES.map((item) => (
              <div
                key={item}
                className="flex items-center gap-2 rounded-full border border-border bg-background px-4 py-3 text-sm"
              >
                <CheckCircle2 className="size-4" />
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* OPERATIONS */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center">
            <div>
              <p className="eyebrow">Long-term performance</p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Installation is only the beginning.
              </h2>

              <p className="mt-5 text-muted-foreground">
                A commercial energy system should be monitored, maintained and
                reviewed throughout its operational life.
              </p>
            </div>

            <div className="grid gap-3 sm:grid-cols-2">
              {[
                {
                  icon: LineChart,
                  title: "Performance monitoring",
                  text: "Track generation and system behaviour.",
                },
                {
                  icon: Wrench,
                  title: "Maintenance",
                  text: "Plan preventative maintenance and intervention.",
                },
                {
                  icon: AlertIcon,
                  title: "Fault response",
                  text: "Identify abnormal performance and investigate issues.",
                },
                {
                  icon: Network,
                  title: "Energy optimisation",
                  text: "Review how the system interacts with site demand.",
                },
              ].map((item) => {
                const Icon = item.icon;

                return (
                  <Card key={item.title}>
                    <CardContent className="p-6">
                      <Icon className="size-5" />

                      <h3 className="mt-5 font-display text-lg font-medium">
                        {item.title}
                      </h3>

                      <p className="mt-2 text-sm leading-6 text-muted-foreground">
                        {item.text}
                      </p>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* ASSESSMENT */}
      <section id="assessment" className="section">
        <div className="container">
          <Card className="mx-auto max-w-4xl overflow-hidden">
            <div className="grid lg:grid-cols-[0.8fr_1.2fr]">
              <div className="bg-black p-8 text-white md:p-10">
                <Building2 className="size-7" />

                <p className="mt-10 font-mono text-[10px] uppercase tracking-[0.2em] text-white/40">
                  Industrial assessment
                </p>

                <h2 className="mt-3 font-display text-3xl font-medium">
                  Let's understand your site.
                </h2>

                <p className="mt-5 text-sm leading-6 text-white/50">
                  Tell us about your building, operation and electricity use.
                  We'll determine which energy opportunities are worth
                  investigating.
                </p>
              </div>

              <div className="p-8 md:p-10">
                <div className="grid gap-3 sm:grid-cols-2">
                  {[
                    "Industrial site",
                    "Annual electricity use",
                    "Roof information",
                    "Operating hours",
                    "Existing solar",
                    "Battery requirements",
                    "EV / fleet plans",
                    "Future expansion",
                  ].map((item, index) => (
                    <div
                      key={item}
                      className="flex items-center gap-3 rounded-xl border border-border p-4"
                    >
                      <span className="font-mono text-[10px] text-muted-foreground">
                        {String(index + 1).padStart(2, "0")}
                      </span>

                      <span className="text-sm">{item}</span>
                    </div>
                  ))}
                </div>

                <Button
                  asChild
                  variant="accent"
                  size="default"
                  className="mt-7 w-full"
                >
                  <Link href="/commercial#assessment">
                    Request an industrial assessment
                    <ArrowRight className="ml-2 size-4" />
                  </Link>
                </Button>
              </div>
            </div>
          </Card>
        </div>
      </section>

      <CtaBanner
        title="Ready to turn your industrial site into an energy asset?"
        description="Let's assess the roof, electricity profile, grid connection and future energy requirements together."
        href="/commercial#assessment"
        cta="Assess your industrial site"
      />
    </>
  );
}

function EnergyNode({
  icon: Icon,
  label,
  value,
}: {
  icon: typeof Sun;
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
      <div className="flex items-center justify-between">
        <Icon className="size-5 text-white/60" />

        <span className="size-2 rounded-full bg-white/70" />
      </div>

      <p className="mt-6 text-xs text-white/35">{label}</p>

      <p className="mt-1 text-sm font-medium">{value}</p>
    </div>
  );
}

function IndustrialStat({
  value,
  label,
}: {
  value: string;
  label: string;
}) {
  return (
    <div className="border-r border-border p-6 last:border-r-0">
      <p className="font-display text-2xl font-medium">{value}</p>

      <p className="mt-1 text-xs text-muted-foreground">{label}</p>
    </div>
  );
}

function MiniMetric({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-xl bg-secondary p-3">
      <p className="text-[10px] text-muted-foreground">{label}</p>

      <p className="mt-1 text-xs font-medium">{value}</p>
    </div>
  );
}

function FutureCard({
  icon: Icon,
  title,
  text,
}: {
  icon: typeof BatteryCharging;
  title: string;
  text: string;
}) {
  return (
    <Card>
      <CardContent className="p-7">
        <div className="flex size-12 items-center justify-center rounded-xl bg-secondary">
          <Icon className="size-5" />
        </div>

        <h3 className="mt-6 font-display text-xl font-medium">
          {title}
        </h3>

        <p className="mt-2 text-sm leading-6 text-muted-foreground">
          {text}
        </p>
      </CardContent>
    </Card>
  );
}

function AlertIcon({
  className,
}: {
  className?: string;
}) {
  return <AlertTriangle className={className} />;
}