import Link from "next/link";
import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  BarChart3,
  BatteryCharging,
  Bell,
  Building2,
  CheckCircle2,
  CircleDollarSign,
  CloudSun,
  FileCheck2,
  Gauge,
  Headphones,
  LineChart,
  LockKeyhole,
  RefreshCw,
  ShieldCheck,
  Sun,
  Wrench,
  Zap,
} from "lucide-react";

import { PageHero } from "@/components/shared/page-hero";
import { CtaBanner } from "@/components/shared/cta-banner";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export const metadata = {
  title: "Commercial Solar Operations & PPA — BrightGrid Energy",
  description:
    "Commercial solar operations, monitoring, maintenance and Power Purchase Agreements designed around long-term energy performance.",
};

const OPERATIONS = [
  {
    icon: Activity,
    number: "01",
    title: "24/7 system monitoring",
    desc: "Generation, inverter behaviour and system performance can be monitored remotely so potential issues can be identified early.",
  },
  {
    icon: AlertTriangle,
    number: "02",
    title: "Fault detection",
    desc: "Performance anomalies can trigger alerts for investigation before they become larger operational problems.",
  },
  {
    icon: Wrench,
    number: "03",
    title: "Planned maintenance",
    desc: "Scheduled inspections and preventative maintenance help keep the energy asset operating as intended.",
  },
  {
    icon: RefreshCw,
    number: "04",
    title: "Repairs & intervention",
    desc: "Where covered by the agreement, required repair and replacement work can be coordinated by the asset owner or operator.",
  },
  {
    icon: LineChart,
    number: "05",
    title: "Performance reporting",
    desc: "Track generation, system performance and relevant operational information throughout the life of the project.",
  },
  {
    icon: Headphones,
    number: "06",
    title: "Operational support",
    desc: "A defined route for questions, incidents and operational matters relating to the energy infrastructure.",
  },
];

const PPA_STEPS = [
  {
    number: "01",
    title: "Assess the opportunity",
    desc: "We assess the building, roof, electricity demand, grid connection, operating profile and potential system size.",
  },
  {
    number: "02",
    title: "Develop the project",
    desc: "The technical design and commercial model are developed around the site's actual requirements.",
  },
  {
    number: "03",
    title: "Agree the funding structure",
    desc: "Where appropriate, an investor or asset owner can provide the capital required to fund the installation.",
  },
  {
    number: "04",
    title: "Build the solar asset",
    desc: "The system is installed, commissioned and connected in accordance with the agreed project requirements.",
  },
  {
    number: "05",
    title: "Generate electricity",
    desc: "The business uses electricity generated by the solar installation under the agreed commercial structure.",
  },
  {
    number: "06",
    title: "Operate & maintain",
    desc: "The asset owner or contracted operator manages responsibilities defined within the PPA and related agreements.",
  },
];

const CUSTOMER_BENEFITS = [
  "No requirement to purchase the entire solar asset upfront",
  "Reduced operational burden for the customer's facilities team",
  "Remote performance monitoring",
  "Planned maintenance coordinated by the asset owner or operator",
  "Fault investigation and intervention under the agreed service structure",
  "Long-term visibility of the energy arrangement",
  "Access to on-site renewable generation",
  "Potential integration with batteries and EV charging",
];

const CUSTOMER_RESPONSIBILITIES = [
  "Operate the site normally",
  "Use the electricity generated by the system",
  "Provide agreed site access",
  "Maintain agreed site conditions",
  "Follow operational requirements",
  "Communicate relevant site changes",
];

const OWNER_RESPONSIBILITIES = [
  "Solar asset ownership",
  "Remote monitoring",
  "Planned maintenance",
  "Fault investigation",
  "Repair coordination",
  "Performance management",
];

export default function CommercialMaintenancePage() {
  return (
    <>
      {/* HERO */}
      <PageHero
        tone="dark"
        eyebrow="Commercial operations & PPA"
        title="You run the business. The energy asset keeps working."
        description="Solar infrastructure shouldn't become another department for your facilities team to manage. With the right ownership and operating structure, the asset can be monitored, maintained and managed throughout its agreement."
        ctaLabel="Discuss a commercial PPA"
        ctaHref="/commercial#assessment"
      />

      {/* ENERGY ASSET INTRO */}
      <section className="section overflow-hidden">
        <div className="container">
          <div className="grid gap-14 lg:grid-cols-[0.85fr_1.15fr] lg:items-center">
            <div>
              <p className="eyebrow">Energy infrastructure as a service</p>

              <h2 className="mt-3 max-w-xl text-balance font-display text-3xl font-medium md:text-5xl">
                Your roof becomes an energy asset. Your team doesn't have to
                become an energy company.
              </h2>

              <p className="mt-6 max-w-xl text-muted-foreground">
                Commercial solar introduces real infrastructure onto a
                property: panels, inverters, monitoring equipment, electrical
                systems and potentially batteries or EV charging.
              </p>

              <p className="mt-4 max-w-xl text-muted-foreground">
                The important question isn't only who installs it. It's who
                owns it, who operates it, who monitors it and who deals with
                problems over the following years.
              </p>

              <Button asChild variant="accent" className="mt-8">
                <Link href="/commercial#assessment">
                  Explore your opportunity
                  <ArrowRight className="ml-2 size-4" />
                </Link>
              </Button>
            </div>

            {/* IMMERSIVE ASSET VISUAL */}
            <div className="relative">
              <div className="relative overflow-hidden rounded-[2rem] border border-border bg-secondary/50 p-5 shadow-sm md:p-8">
                <div className="absolute -right-20 -top-20 size-64 rounded-full border border-border/60" />
                <div className="absolute -bottom-32 -left-20 size-72 rounded-full border border-border/50" />

                <div className="relative">
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
                        Energy asset
                      </p>

                      <h3 className="mt-2 font-display text-2xl font-medium">
                        Commercial solar system
                      </h3>
                    </div>

                    <Badge variant="leaf">Operational</Badge>
                  </div>

                  <div className="mt-8 rounded-2xl border border-border bg-background p-5">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="flex size-10 items-center justify-center rounded-xl bg-secondary">
                          <Sun className="size-5" />
                        </div>

                        <div>
                          <p className="text-sm font-medium">
                            Solar generation
                          </p>
                          <p className="text-xs text-muted-foreground">
                            On-site renewable electricity
                          </p>
                        </div>
                      </div>

                      <span className="flex items-center gap-2 text-xs font-medium">
                        <span className="size-2 rounded-full bg-green-500" />
                        Online
                      </span>
                    </div>

                    <div className="mt-6 h-24 overflow-hidden rounded-xl border border-border bg-secondary/50">
                      <div className="flex h-full items-end gap-1 px-4 pb-3">
                        {[35, 42, 28, 55, 63, 52, 72, 61, 80, 68, 88, 74].map(
                          (height, index) => (
                            <div
                              key={index}
                              className="flex-1 rounded-t bg-foreground/70"
                              style={{ height: `${height}%` }}
                            />
                          ),
                        )}
                      </div>
                    </div>

                    <div className="mt-4 grid grid-cols-3 gap-2">
                      <MiniMetric label="Generation" value="Active" />
                      <MiniMetric label="Monitoring" value="Live" />
                      <MiniMetric label="Maintenance" value="Current" />
                    </div>
                  </div>

                  <div className="my-4 flex justify-center">
                    <ArrowDown className="size-5 text-muted-foreground" />
                  </div>

                  <div className="grid gap-3 sm:grid-cols-3">
                    <AssetNode
                      icon={LineChart}
                      title="Monitor"
                      text="Performance"
                    />

                    <AssetNode
                      icon={Wrench}
                      title="Maintain"
                      text="Infrastructure"
                    />

                    <AssetNode
                      icon={ShieldCheck}
                      title="Manage"
                      text="Asset lifecycle"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FULL-WIDTH ENERGY FLOW */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="mx-auto max-w-3xl text-center">
            <p className="eyebrow">The operating model</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              From sunlight to electricity to managed infrastructure.
            </h2>

            <p className="mt-5 text-muted-foreground">
              A commercial solar project has a lifecycle. The best operating
              model makes every stage visible.
            </p>
          </div>

          <div className="mx-auto mt-12 max-w-6xl">
            <div className="grid gap-3 md:grid-cols-5">
              <FlowNode
                icon={Sun}
                number="01"
                title="Generate"
                description="Solar converts sunlight into electricity."
              />

              <FlowArrow />

              <FlowNode
                icon={Building2}
                number="02"
                title="Use"
                description="Power is consumed by the business."
              />

              <FlowArrow />

              <FlowNode
                icon={LineChart}
                number="03"
                title="Monitor"
                description="System performance is continuously observed."
              />
            </div>

            <div className="mx-auto my-4 hidden justify-center md:flex">
              <ArrowDown className="size-5 text-muted-foreground" />
            </div>

            <div className="grid gap-3 md:grid-cols-5">
              <FlowNode
                icon={AlertTriangle}
                number="04"
                title="Detect"
                description="Potential anomalies are identified."
              />

              <FlowArrow />

              <FlowNode
                icon={Wrench}
                number="05"
                title="Maintain"
                description="Planned and corrective work is coordinated."
              />

              <FlowArrow />

              <FlowNode
                icon={ShieldCheck}
                number="06"
                title="Protect"
                description="The asset continues through its operating life."
              />
            </div>
          </div>
        </div>
      </section>

      {/* DASHBOARD */}
      <section className="section">
        <div className="container">
          <div className="mx-auto max-w-6xl overflow-hidden rounded-[2rem] border border-border bg-black text-white shadow-2xl">
            <div className="relative overflow-hidden">
              <div className="absolute right-0 top-0 size-72 rounded-full bg-white/[0.03] blur-3xl" />

              <div className="relative border-b border-white/10 p-6 md:p-8">
                <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-white/40">
                      Commercial energy operations
                    </p>

                    <h3 className="mt-2 font-display text-2xl font-medium">
                      Example asset control centre
                    </h3>
                  </div>

                  <Badge variant="leaf">System operating normally</Badge>
                </div>
              </div>

              <div className="relative grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-4">
                <DarkMetric
                  icon={Sun}
                  label="Solar generation"
                  value="Online"
                  status="Generating"
                />

                <DarkMetric
                  icon={BatteryCharging}
                  label="Battery"
                  value="Available"
                  status="Standby"
                />

                <DarkMetric
                  icon={Gauge}
                  label="Performance"
                  value="Within range"
                  status="Healthy"
                />

                <DarkMetric
                  icon={ShieldCheck}
                  label="Maintenance"
                  value="Up to date"
                  status="No action"
                />
              </div>

              <div className="relative grid gap-8 border-t border-white/10 p-6 md:grid-cols-[1fr_0.7fr] md:p-8">
                <div>
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-xs text-white/40">
                        Illustrative generation profile
                      </p>

                      <p className="mt-1 text-lg font-medium">
                        Daily performance
                      </p>
                    </div>

                    <BarChart3 className="size-5 text-white/40" />
                  </div>

                  <div className="mt-6 flex h-40 items-end gap-1 rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                    {[18, 22, 25, 32, 44, 58, 70, 82, 88, 92, 84, 72, 62, 50, 42, 30, 22, 14].map(
                      (height, index) => (
                        <div
                          key={index}
                          className="flex-1 rounded-t bg-white/70"
                          style={{ height: `${height}%` }}
                        />
                      ),
                    )}
                  </div>
                </div>

                <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
                  <div className="flex items-center gap-3">
                    <Bell className="size-5 text-white/60" />

                    <div>
                      <p className="text-sm font-medium">Latest events</p>
                      <p className="text-xs text-white/40">
                        Example operational feed
                      </p>
                    </div>
                  </div>

                  <div className="mt-6 space-y-4">
                    <EventRow
                      title="Generation normal"
                      time="09:42"
                      icon={CheckCircle2}
                    />

                    <EventRow
                      title="Inverter reporting"
                      time="09:35"
                      icon={Activity}
                    />

                    <EventRow
                      title="Monitoring active"
                      time="09:00"
                      icon={ShieldCheck}
                    />
                  </div>
                </div>
              </div>

              <div className="border-t border-white/10 px-6 py-5 text-xs leading-5 text-white/40 md:px-8">
                Illustrative interface only. Actual monitoring, controls,
                telemetry and service responsibilities depend on the installed
                equipment and executed service agreement.
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* OPERATIONS */}
      <section id="operations" className="section bg-secondary/50">
        <div className="container">
          <div className="max-w-2xl">
            <p className="eyebrow">Ongoing operations</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              The installation is only the beginning.
            </h2>

            <p className="mt-5 text-muted-foreground">
              Solar is a long-term infrastructure asset. Monitoring,
              maintenance and operational support are what turn an installation
              into an actively managed energy system.
            </p>
          </div>

          <div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">
            {OPERATIONS.map((item) => {
              const Icon = item.icon;

              return (
                <div
                  key={item.title}
                  className="group bg-background p-7 transition-all duration-300 hover:bg-secondary"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex size-11 items-center justify-center rounded-xl bg-secondary group-hover:bg-background">
                      <Icon className="size-5" />
                    </div>

                    <span className="font-mono text-xs text-muted-foreground">
                      {item.number}
                    </span>
                  </div>

                  <h3 className="mt-7 font-display text-xl font-medium">
                    {item.title}
                  </h3>

                  <p className="mt-3 text-sm leading-6 text-muted-foreground">
                    {item.desc}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* PPA HERO */}
      <section id="ppa" className="section overflow-hidden bg-black text-white">
        <div className="container">
          <div className="relative">
            <div className="pointer-events-none absolute -right-40 -top-40 size-[500px] rounded-full border border-white/[0.06]" />
            <div className="pointer-events-none absolute -right-20 -top-20 size-[340px] rounded-full border border-white/[0.06]" />

            <div className="relative grid gap-14 lg:grid-cols-[0.8fr_1.2fr]">
              <div>
                <div className="flex size-12 items-center justify-center rounded-2xl border border-white/10 bg-white/[0.05]">
                  <CircleDollarSign className="size-6" />
                </div>

                <p className="mt-7 font-mono text-[10px] uppercase tracking-[0.2em] text-white/40">
                  Power Purchase Agreement
                </p>

                <h2 className="mt-3 max-w-xl text-balance font-display text-3xl font-medium md:text-5xl">
                  What if you want the electricity, but don't want to own the
                  asset?
                </h2>

                <p className="mt-6 max-w-md leading-7 text-white/55">
                  A PPA can separate the financing and ownership of the solar
                  installation from the organisation using the electricity.
                </p>

                <Button
                  asChild
                  variant="outline"
                  className="mt-8 border-white/20 bg-white text-black hover:bg-white/90"
                >
                  <Link href="/commercial#assessment">
                    Explore a PPA
                    <ArrowRight className="ml-2 size-4" />
                  </Link>
                </Button>

                <div className="mt-10 flex items-center gap-3 text-xs text-white/40">
                  <LockKeyhole className="size-4" />
                  Commercial terms are site and contract specific.
                </div>
              </div>

              <div className="relative">
                <div className="absolute left-6 top-10 hidden h-[calc(100%-80px)] w-px bg-white/10 md:block" />

                <div className="space-y-1">
                  {PPA_STEPS.map((step) => (
                    <div
                      key={step.number}
                      className="group relative grid gap-5 rounded-2xl border border-transparent p-5 transition-colors hover:border-white/10 hover:bg-white/[0.04] md:grid-cols-[55px_1fr]"
                    >
                      <div className="relative z-10 flex size-12 items-center justify-center rounded-full border border-white/10 bg-black font-mono text-xs text-white/50">
                        {step.number}
                      </div>

                      <div className="pt-1">
                        <h3 className="font-display text-xl font-medium">
                          {step.title}
                        </h3>

                        <p className="mt-2 max-w-xl text-sm leading-6 text-white/50">
                          {step.desc}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* PPA VISUAL ECONOMICS */}
      <section className="section">
        <div className="container">
          <div className="mx-auto max-w-4xl text-center">
            <p className="eyebrow">The commercial idea</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              Turn a capital project into a long-term energy relationship.
            </h2>

            <p className="mx-auto mt-5 max-w-2xl text-muted-foreground">
              Instead of viewing solar purely as an equipment purchase, a PPA
              can structure the project around electricity generation,
              ownership, operation and long-term commercial terms.
            </p>
          </div>

          <div className="mx-auto mt-12 max-w-5xl">
            <div className="grid overflow-hidden rounded-3xl border border-border md:grid-cols-3">
              <CommercialNode
                icon={CircleDollarSign}
                number="01"
                title="Capital"
                description="Funding is arranged for the solar asset according to the agreed commercial structure."
              />

              <CommercialNode
                icon={Sun}
                number="02"
                title="Generation"
                description="The installed solar system generates electricity at the customer's site."
              />

              <CommercialNode
                icon={LineChart}
                number="03"
                title="Long-term value"
                description="The agreement defines how electricity, pricing, operation and responsibilities are managed."
              />
            </div>
          </div>
        </div>
      </section>

      {/* RESPONSIBILITY SPLIT */}
      <section className="section bg-secondary/50">
        <div className="container">
          <div className="mx-auto max-w-3xl text-center">
            <p className="eyebrow">Who does what?</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              Clear responsibilities make long-term projects easier to manage.
            </h2>

            <p className="mt-5 text-muted-foreground">
              The exact split depends on the executed PPA and related
              agreements, but the principle is simple: responsibilities should
              be clear before the system starts operating.
            </p>
          </div>

          <div className="mx-auto mt-12 grid max-w-6xl overflow-hidden rounded-[2rem] border border-border md:grid-cols-2">
            {/* BUSINESS */}
            <div className="bg-background p-8 md:p-10">
              <div className="flex items-center justify-between">
                <div className="flex size-12 items-center justify-center rounded-xl bg-secondary">
                  <Building2 className="size-6" />
                </div>

                <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
                  Customer
                </span>
              </div>

              <h3 className="mt-7 font-display text-2xl font-medium">
                Your business
              </h3>

              <p className="mt-2 text-sm leading-6 text-muted-foreground">
                Continue operating the property while using the agreed energy
                arrangement.
              </p>

              <div className="mt-8 space-y-4">
                {CUSTOMER_RESPONSIBILITIES.map((item) => (
                  <ResponsibilityItem key={item} text={item} />
                ))}
              </div>
            </div>

            {/* OWNER */}
            <div className="border-t border-border bg-black p-8 text-white md:border-l md:border-t-0 md:p-10">
              <div className="flex items-center justify-between">
                <div className="flex size-12 items-center justify-center rounded-xl bg-white/10">
                  <ShieldCheck className="size-6" />
                </div>

                <span className="font-mono text-[10px] uppercase tracking-widest text-white/40">
                  Asset owner / operator
                </span>
              </div>

              <h3 className="mt-7 font-display text-2xl font-medium">
                Energy asset
              </h3>

              <p className="mt-2 text-sm leading-6 text-white/45">
                Responsibilities are defined by the PPA and operating
                agreements.
              </p>

              <div className="mt-8 space-y-4">
                {OWNER_RESPONSIBILITIES.map((item) => (
                  <div
                    key={item}
                    className="flex items-start gap-3 text-sm text-white/75"
                  >
                    <CheckCircle2 className="mt-0.5 size-4 shrink-0" />
                    {item}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* BENEFITS */}
      <section className="section">
        <div className="container">
          <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-start">
            <div className="lg:sticky lg:top-28">
              <p className="eyebrow">Why businesses consider a PPA</p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Access renewable generation without creating a solar
                operations department.
              </h2>

              <p className="mt-5 max-w-xl text-muted-foreground">
                This can be particularly relevant for businesses managing
                multiple properties, large facilities or capital-intensive
                operations.
              </p>
            </div>

            <div className="grid gap-3">
              {CUSTOMER_BENEFITS.map((benefit, index) => (
                <div
                  key={benefit}
                  className="group flex items-start gap-4 rounded-2xl border border-border bg-background p-5 transition-all hover:-translate-y-0.5 hover:bg-secondary"
                >
                  <span className="font-mono text-xs text-muted-foreground">
                    {String(index + 1).padStart(2, "0")}
                  </span>

                  <div className="flex gap-3">
                    <CheckCircle2 className="mt-0.5 size-4 shrink-0" />

                    <span className="text-sm leading-6">{benefit}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* LIFECYCLE */}
      <section className="section bg-black text-white">
        <div className="container">
          <div className="mx-auto max-w-3xl text-center">
            <p className="eyebrow text-white/50">Asset lifecycle</p>

            <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
              The relationship continues long after installation day.
            </h2>

            <p className="mt-5 text-white/50">
              A commercial solar project should be designed with its full
              operating life in mind.
            </p>
          </div>

          <div className="mx-auto mt-12 max-w-5xl">
            <div className="grid gap-3 md:grid-cols-5">
              <Lifecycle
                icon={FileCheck2}
                title="Agreement"
                text="Commercial terms defined."
              />

              <Lifecycle
                icon={Sun}
                title="Installation"
                text="System built and commissioned."
              />

              <Lifecycle
                icon={Activity}
                title="Operation"
                text="Generation monitored."
              />

              <Lifecycle
                icon={Wrench}
                title="Maintenance"
                text="Asset maintained."
              />

              <Lifecycle
                icon={RefreshCw}
                title="Review"
                text="Long-term arrangements managed."
              />
            </div>
          </div>
        </div>
      </section>

      {/* COMMERCIAL DETAILS */}
      <section className="section">
        <div className="container">
          <div className="mx-auto max-w-4xl rounded-[2rem] border border-border bg-secondary/40 p-8 md:p-12">
            <div className="flex flex-col gap-8 md:flex-row">
              <div className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-background">
                <FileCheck2 className="size-6" />
              </div>

              <div>
                <p className="eyebrow">Commercial structure</p>

                <h2 className="mt-3 font-display text-2xl font-medium md:text-4xl">
                  The details matter.
                </h2>

                <p className="mt-5 text-sm leading-7 text-muted-foreground">
                  Every PPA is different. Ownership, maintenance, insurance,
                  performance guarantees, site access, electricity pricing,
                  contract duration, termination provisions and end-of-term
                  arrangements should all be clearly defined.
                </p>

                <p className="mt-4 text-sm leading-7 text-muted-foreground">
                  The final contractual responsibilities are determined by the
                  executed PPA and related agreements. Technical and commercial
                  assumptions should be tested against the actual site before
                  committing to a structure.
                </p>

                <div className="mt-8 grid gap-3 sm:grid-cols-2">
                  <DetailPill
                    icon={FileCheck2}
                    text="Contract structure"
                  />

                  <DetailPill
                    icon={CircleDollarSign}
                    text="Energy pricing"
                  />

                  <DetailPill
                    icon={ShieldCheck}
                    text="Performance obligations"
                  />

                  <DetailPill
                    icon={Wrench}
                    text="Maintenance responsibility"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ASSESSMENT CTA */}
      <section id="assessment" className="section">
        <div className="container">
          <div className="relative overflow-hidden rounded-[2rem] bg-secondary p-8 md:p-12">
            <div className="absolute -right-20 -top-20 size-64 rounded-full border border-border" />
            <div className="absolute -bottom-28 right-20 size-80 rounded-full border border-border/60" />

            <div className="relative max-w-3xl">
              <p className="eyebrow">Start with your site</p>

              <h2 className="mt-3 text-balance font-display text-3xl font-medium md:text-5xl">
                Let's find out whether a commercial PPA could work for you.
              </h2>

              <p className="mt-5 max-w-2xl text-muted-foreground">
                Tell us about the property, electricity demand, operational
                requirements and your preferred commercial structure. We'll
                help identify the most appropriate next step.
              </p>

              <Button asChild variant="accent" size="default" className="mt-8">
                <Link href="/commercial/assessment">
                  Request a commercial assessment
                  <ArrowRight className="ml-2 size-4" />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      <CtaBanner
        title="Want solar without taking on the asset?"
        description="Let's explore your site, energy demand and whether an externally funded PPA structure could make sense."
        href="/commercial#assessment"
        cta="Discuss a commercial PPA"
      />
    </>
  );
}

/* -------------------------------------------------------------------------- */
/* COMPONENTS                                                                 */
/* -------------------------------------------------------------------------- */

function MiniMetric({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-lg border border-border bg-secondary/50 p-3">
      <p className="text-[10px] text-muted-foreground">{label}</p>
      <p className="mt-1 text-xs font-medium">{value}</p>
    </div>
  );
}

function AssetNode({
  icon: Icon,
  title,
  text,
}: {
  icon: typeof LineChart;
  title: string;
  text: string;
}) {
  return (
    <div className="rounded-xl border border-border bg-background p-4">
      <Icon className="size-5" />

      <p className="mt-4 text-sm font-medium">{title}</p>

      <p className="mt-1 text-xs text-muted-foreground">{text}</p>
    </div>
  );
}

function FlowNode({
  icon: Icon,
  number,
  title,
  description,
}: {
  icon: typeof Sun;
  number: string;
  title: string;
  description: string;
}) {
  return (
    <div className="rounded-2xl border border-border bg-background p-5">
      <div className="flex items-center justify-between">
        <div className="flex size-10 items-center justify-center rounded-xl bg-secondary">
          <Icon className="size-5" />
        </div>

        <span className="font-mono text-[10px] text-muted-foreground">
          {number}
        </span>
      </div>

      <h3 className="mt-5 font-display text-lg font-medium">{title}</h3>

      <p className="mt-2 text-xs leading-5 text-muted-foreground">
        {description}
      </p>
    </div>
  );
}

function FlowArrow() {
  return (
    <div className="hidden items-center justify-center md:flex">
      <ArrowRight className="size-5 text-muted-foreground" />
    </div>
  );
}

function DarkMetric({
  icon: Icon,
  label,
  value,
  status,
}: {
  icon: typeof Sun;
  label: string;
  value: string;
  status: string;
}) {
  return (
    <div className="bg-black p-6">
      <div className="flex items-center justify-between">
        <Icon className="size-5 text-white/50" />

        <span className="flex items-center gap-1.5 text-[10px] text-white/35">
          <span className="size-1.5 rounded-full bg-white/60" />
          {status}
        </span>
      </div>

      <p className="mt-6 text-xs text-white/35">{label}</p>

      <p className="mt-1 font-medium">{value}</p>
    </div>
  );
}

function EventRow({
  icon: Icon,
  title,
  time,
}: {
  icon: typeof CheckCircle2;
  title: string;
  time: string;
}) {
  return (
    <div className="flex items-center justify-between border-b border-white/10 pb-3 last:border-0 last:pb-0">
      <div className="flex items-center gap-3">
        <Icon className="size-4 text-white/50" />

        <span className="text-sm text-white/70">{title}</span>
      </div>

      <span className="font-mono text-[10px] text-white/30">{time}</span>
    </div>
  );
}

function CommercialNode({
  icon: Icon,
  number,
  title,
  description,
}: {
  icon: typeof CircleDollarSign;
  number: string;
  title: string;
  description: string;
}) {
  return (
    <div className="group border-b border-border p-7 transition-colors hover:bg-secondary md:border-b-0 md:border-r last:border-r-0">
      <div className="flex items-center justify-between">
        <div className="flex size-11 items-center justify-center rounded-xl bg-secondary group-hover:bg-background">
          <Icon className="size-5" />
        </div>

        <span className="font-mono text-xs text-muted-foreground">
          {number}
        </span>
      </div>

      <h3 className="mt-7 font-display text-xl font-medium">{title}</h3>

      <p className="mt-3 text-sm leading-6 text-muted-foreground">
        {description}
      </p>
    </div>
  );
}

function ResponsibilityItem({
  text,
}: {
  text: string;
}) {
  return (
    <div className="flex items-start gap-3 text-sm">
      <CheckCircle2 className="mt-0.5 size-4 shrink-0" />
      <span>{text}</span>
    </div>
  );
}

function Lifecycle({
  icon: Icon,
  title,
  text,
}: {
  icon: typeof FileCheck2;
  title: string;
  text: string;
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5">
      <Icon className="size-5 text-white/60" />

      <h3 className="mt-5 font-display text-lg font-medium">{title}</h3>

      <p className="mt-2 text-xs leading-5 text-white/40">{text}</p>
    </div>
  );
}

function DetailPill({
  icon: Icon,
  text,
}: {
  icon: typeof FileCheck2;
  text: string;
}) {
  return (
    <div className="flex items-center gap-3 rounded-xl border border-border bg-background p-4 text-sm font-medium">
      <Icon className="size-4 shrink-0" />
      {text}
    </div>
  );
}